# Generated by Django 5.0.4 on 2024-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
