# Generated by Django 4.2.13 on 2024-05-14 08:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
        migrations.DeleteModel(
            name='PortfolioImageUploadFragment',
        ),
    ]
