# Generated by Django 5.0.4 on 2024-05-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_socialmedia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformbaseuser',
            name='joined',
        ),
    ]
