# Generated by Django 5.0.4 on 2024-05-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_platformbaseuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='username',
        ),
    ]
