# Generated by Django 4.2.13 on 2024-05-14 09:45

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_product_image_filename),
        ),
        migrations.AddField(
            model_name='advertiserproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_product_image_filename),
        ),
        migrations.AddField(
            model_name='advertiserproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_product_image_filename),
        ),
        migrations.AlterField(
            model_name='advertiserproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProductImageUploadFragment',
        ),
    ]
