# Generated by Django 5.0.4 on 2024-05-09 22:14

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_platformbaseuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbaseuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_filename),
        ),
    ]
