# Generated by Django 5.0.4 on 2024-05-10 01:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_platformbaseuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_advertiser_product_image_filename),
        ),
        migrations.AlterField(
            model_name='advertiserproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='platformbaseuser',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_banner_image_filename),
        ),
        migrations.AlterField(
            model_name='platformbaseuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_profile_image_filename),
        ),
    ]
