# Generated by Django 5.0.4 on 2024-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_advertiserproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
