# Generated by Django 5.0.4 on 2024-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_advertiserproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
