# Generated by Django 4.2.13 on 2024-05-22 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240522_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adspaceforspacehost',
            name='temp_id',
        ),
        migrations.AlterField(
            model_name='adspaceforspacehost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
