# Generated by Django 5.0.4 on 2024-05-10 01:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_advertiserproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_advertiser_product_image_filename),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='file_url',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
    ]
