# Generated by Django 5.0.4 on 2024-05-10 02:08

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_advertiserproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserproduct',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=users.models.change_advertiser_product_image_filename),
        ),
    ]
