# Generated by Django 5.0.4 on 2024-05-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_advertiserproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='file_url',
        ),
        migrations.CreateModel(
            name='PortfolioImageUploadFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.portfolio')),
            ],
        ),
    ]
