# Generated by Django 5.0.4 on 2024-05-10 15:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_portfolio_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimageuploadfragment',
            name='file',
            field=models.ImageField(upload_to=users.models.change_portfolio_image_filename),
        ),
    ]
