# Generated by Django 5.0.4 on 2024-05-10 16:22

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_portfolioimageuploadfragment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserproduct',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImageUploadFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=users.models.change_product_image_filename)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.advertiserproduct')),
            ],
        ),
    ]
