# Generated by Django 5.0.4 on 2024-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('space_host', 'Space Host'), ('advertiser', 'Advertiser')], max_length=20, null=True),
        ),
    ]
